#!/usr/bin/env ruby
require "yaml"

class GitHubPRCreator
  CONFIG_FILE = ".gh-feature-config.yml"
  DEFAULT_BASE_BRANCH = "staging"

  def initialize
    @config = load_config
    @feature_name = feature_name
    @label = @config.dig(@feature_name, "label")
    @reviewers = @config.dig(@feature_name, "reviewers")
  end

  def self.create
    new.create
  end

  def create
    exec(*build_pr_command)
  end

  private

  def load_config
    config_path = File.join(Dir.pwd, CONFIG_FILE)
    abort("❌ Configuration file #{CONFIG_FILE} not found.") unless File.exist?(config_path)

    YAML.load_file(config_path)
  end

  def feature_name
    branch = `git rev-parse --abbrev-ref HEAD`.strip
    parsed = branch.match(/^(?:conflict(s?)\/)?(?<ticket>[^\/]+)\/(?<feature>[^\/]+)\/(?<title>[^\/]+)$/i)

    abort("❌ Branch name must be in the format '<ticket>/<feature>/<title>' or 'conflicts/<ticket>/<feature>/<title>'") if parsed.nil?
    parsed[:feature]
  end

  def build_pr_command
    command = ["gh", "pr", "create", "-B", DEFAULT_BASE_BRANCH]
    command += ["--label", @label] if @label
    command += ["--reviewer", @reviewers.join(",")] if @reviewers.any?
    command += ["--assignee", "@me"]
    command + ARGV
  end
end

GitHubPRCreator.create
